### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by georgemsaad** [clifgriffin/simple-ldap-login#33]
Hello when I download the plugin I get the following error

Fatal error: Uncaught exception 'adLDAPException' with message 'No LDAP support for PHP. See: http://www.php.net/ldap' in /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-content/plugins/simple-ldap-login/includes/adLDAP.php:338 Stack trace: #0 /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php(34): adLDAP->__construct(Array) #1 /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php(61): SimpleLDAPLogin->__construct() #2 /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php(563): SimpleLDAPLogin::getInstance() #3 /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-admin/includes/plugin.php(1934): include('/home/content/p...') #4 /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-admin/plugins.php(164): plugin_sandbox_scrape('simple-ldap-log...') #5 {main} thrown in /home/content/p3pnexwpnas13_data01/10/3032010/html/wp-content/plugins/simple-ldap-login/includes/adLDAP.php on line 338

**Comment by tmertz** [comment]
Remember to run "apt-get install php-ldap" for your server.

**Comment by jpuck** [comment]
having php-ldap installed on the server needs to be documented in the requirements/installation instructions

**Comment by Elompenta** [comment]
fixed in https://github.com/Elompenta/simple-ldap-login/commit/d9597ab66e59fec4bebd3bd267762a6a0197f384
