### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by craigtommola** [clifgriffin/simple-ldap-login#58]
I've been using SimpleLDAP (simply) for years. But it hasn't been tested or updated in quite some time. I began ("proactively") looking for an alternative, only to find not many good (simple) options. 

Then in running updates (on dev, thankfully) I received what I was trying to avoid ...

Fatal error: Uncaught Error: Call to undefined function ldap_connect() in /data/blogs/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php:368 Stack trace: #0 /data/blogs/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php(300): SimpleLDAPLogin->ldap_auth() #1 /data/blogs/wp-includes/class-wp-hook.php(287): SimpleLDAPLogin->authenticate() #2 /data/blogs/wp-includes/plugin.php(206): WP_Hook->apply_filters() #3 /data/blogs/wp-includes/pluggable.php(549): apply_filters() #4 /data/blogs/wp-includes/user.php(95): wp_authenticate() #5 /data/blogs/wp-login.php(1248): wp_signon() #6 {main} thrown in /data/blogs/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php on line 368

Any thoughts on this? Or continued maintenance of the plugin? 

Thank you kindly. It's served us well.

**Comment by Fausztusz** [comment]
Hi!

I had the same problem. I believe it happens, when you try to set more than one **Domain Controller**. 

You can try to hack a proper method, to split the URLs, or just don't use a fallback host.

This repo is pretty much dead, so I wouldn't hold my breath waiting for a patch.
